In [1]:
# Import Python Libraries
import numpy as np

In [2]:
#Take two sets of patterns:
# Set A: Input Pattern
x1 = np.array([1, 1, 1, 1, 1, 1]).reshape(6, 1)
x2 = np.array([-1, -1, -1, -1, -1, -1]).reshape(6, 1)
x3 = np.array([1, 1, -1, -1, 1, 1]).reshape(6, 1)
x4 = np.array([-1, -1, 1, 1, -1, -1]).reshape(6, 1)

In [3]:
print(f"x1 : \n{x1}\n\nx2 : \n{x2}\n\nx3 : \n{x3}\n\nx4 : \n{x4}")

x1 : 
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]

x2 : 
[[-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]]

x3 : 
[[ 1]
 [ 1]
 [-1]
 [-1]
 [ 1]
 [ 1]]

x4 : 
[[-1]
 [-1]
 [ 1]
 [ 1]
 [-1]
 [-1]]


In [4]:
# Set B: Target Pattern
y1 = np.array([1, 1, 1]).reshape(3, 1)
y2 = np.array([-1, -1, -1]).reshape(3, 1)
y3 = np.array([1, -1, 1]).reshape(3, 1)
y4 = np.array([-1, 1, -1]).reshape(3, 1)

In [5]:
print(f"y1 : \n{y1}\n\ny2 : \n{y2}\n\ny3 : \n{y3}\n\ny4 : \n{y4}")

y1 : 
[[1]
 [1]
 [1]]

y2 : 
[[-1]
 [-1]
 [-1]]

y3 : 
[[ 1]
 [-1]
 [ 1]]

y4 : 
[[-1]
 [ 1]
 [-1]]


In [6]:
# concatenate input pattern
inputSet = np.concatenate((x1, x2, x3, x4), axis = 1)
print(inputSet)

[[ 1 -1  1 -1]
 [ 1 -1  1 -1]
 [ 1 -1 -1  1]
 [ 1 -1 -1  1]
 [ 1 -1  1 -1]
 [ 1 -1  1 -1]]


In [7]:
# concatenate target pattern
targetSet = np.concatenate((y1.T, y2.T, y3.T, y4.T), axis = 0)
print(targetSet)

[[ 1  1  1]
 [-1 -1 -1]
 [ 1 -1  1]
 [-1  1 -1]]


In [8]:
print("Weight matrix:")
weight = np.dot(inputSet, targetSet)
print(weight)

Weight matrix:
[[4 0 4]
 [4 0 4]
 [0 4 0]
 [0 4 0]
 [4 0 4]
 [4 0 4]]


In [9]:
def testInputs(x, weight):
  # Multiply the input pattern with the weight matrix
  y = np.dot(weight.T, x)
  y[y < 0] = -1
  y[y >= 0] = 1
  return np.array(y)

In [10]:
print("\nOutput of input pattern 1")
print(testInputs(x1, weight))
print("\nOutput of input pattern 2")
print(testInputs(x2, weight))
print("\nOutput of input pattern 3")
print(testInputs(x3, weight))
print("\nOutput of input pattern 4")
print(testInputs(x4, weight))


Output of input pattern 1
[[1]
 [1]
 [1]]

Output of input pattern 2
[[-1]
 [-1]
 [-1]]

Output of input pattern 3
[[ 1]
 [-1]
 [ 1]]

Output of input pattern 4
[[-1]
 [ 1]
 [-1]]


In [11]:
y = np.dot(weight.T, x4)
print(y)

[[-16]
 [  8]
 [-16]]


In [12]:
y[y < 0] = -1
print(y[y < 0])

[-1 -1]


In [13]:
print(y < 0)

[[ True]
 [False]
 [ True]]


In [14]:
y[y >= 0] = 1
print(y[y >= 0])

[1]


In [15]:
print(np.array(y))

[[-1]
 [ 1]
 [-1]]


In [16]:
def testTargets(y, weight):
  # Multiply the target pattern with the weight matrix
  # (weight X y)
  x = np.dot(weight, y)
  x[x <= 0] = -1
  x[x > 0] = 1
  return np.array(x)

In [17]:
print("Output of target pattern 1")
print(testTargets(y1, weight))
print("\nOutput of target pattern 2")
print(testTargets(y2, weight))
print("\nOutput of target pattern 3")
print(testTargets(y3, weight))
print("\nOutput of target pattern 4")
print(testTargets(y4, weight))

print("\nName : Shantanu Anant Gaikwad\nRoll No : 27")

Output of target pattern 1
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]

Output of target pattern 2
[[-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]]

Output of target pattern 3
[[ 1]
 [ 1]
 [-1]
 [-1]
 [ 1]
 [ 1]]

Output of target pattern 4
[[-1]
 [-1]
 [ 1]
 [ 1]
 [-1]
 [-1]]

Name : Shantanu Anant Gaikwad
Roll No : 27
